// frontend/src/components/ReportHistory.jsx
import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';

export default function ReportHistory({ onViewDashboard }) {
  const { user, clients, activeClient, activeLocation, isAdmin } = useAuth();
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [clientFilter, setClientFilter] = useState(activeClient?.id || 'all');
  const [locationFilter, setLocationFilter] = useState('ALL');
  const [searchQuery, setSearchQuery] = useState('');

  const fetchHistory = async () => {
    try {
      setLoading(true);
      const queryParams = new URLSearchParams();
      if (clientFilter && clientFilter !== 'all') queryParams.append('clientId', clientFilter);
      if (locationFilter && locationFilter !== 'ALL' && locationFilter !== 'All Locations') {
        queryParams.append('location', locationFilter);
      }

      const res = await fetch(`/api/history?${queryParams.toString()}`);
      if (res.ok) {
        const json = await res.json();
        setHistory(json.history || []);
      }
    } catch (err) {
      console.error('Error fetching history:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchHistory();
  }, [clientFilter, locationFilter]);

  const filteredHistory = history.filter((item) => {
    if (!searchQuery) return true;
    const q = searchQuery.toLowerCase();
    return (
      item.jobId.toLowerCase().includes(q) ||
      item.clientName.toLowerCase().includes(q) ||
      item.location.toLowerCase().includes(q) ||
      item.uploadedBy.toLowerCase().includes(q)
    );
  });

  return (
    <div className="history-container">
      <div className="card">
        <div className="card-header border-bottom">
          <div>
            <h2 className="card-title">📜 Generated Reports History</h2>
            <p className="card-subtitle">
              Audit log of executive report generation metadata. No raw ticket or inventory data is retained per strict data policy.
            </p>
          </div>
          <button className="btn-secondary" onClick={fetchHistory}>
            🔄 Refresh Log
          </button>
        </div>

        {/* Filters Bar */}
        <div className="filters-bar">
          <div className="filter-group">
            <label>Client Filter:</label>
            <select
              value={clientFilter}
              onChange={(e) => setClientFilter(e.target.value)}
              className="select-field"
            >
              <option value="all">All Clients</option>
              {clients.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.logo} {c.name}
                </option>
              ))}
            </select>
          </div>

          <div className="filter-group">
            <label>Location:</label>
            <input
              type="text"
              placeholder="Filter by site..."
              value={locationFilter === 'ALL' ? '' : locationFilter}
              onChange={(e) => setLocationFilter(e.target.value || 'ALL')}
              className="input-field"
            />
          </div>

          <div className="filter-group search-group">
            <label>Search:</label>
            <input
              type="text"
              placeholder="Search user, client, ID..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="input-field"
            />
          </div>
        </div>

        {/* History Table */}
        {loading ? (
          <div className="loading-state">Loading history metadata...</div>
        ) : filteredHistory.length === 0 ? (
          <div className="empty-state">
            <div className="empty-icon">📂</div>
            <h4>No report metadata found</h4>
            <p>Upload files from the "Upload & Generate" tab to generate executive dashboards.</p>
          </div>
        ) : (
          <div className="table-wrapper">
            <table className="data-table history-table">
              <thead>
                <tr>
                  <th>Client</th>
                  <th>Location</th>
                  <th>Period</th>
                  <th>Upload Date</th>
                  <th>Generated By</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredHistory.map((item) => (
                  <tr key={item.jobId}>
                    <td>
                      <div className="client-cell">
                        <span className="client-badge">{item.clientName}</span>
                      </div>
                    </td>
                    <td>📍 {item.location}</td>
                    <td>📅 {item.reportPeriod}</td>
                    <td>{new Date(item.uploadTimestamp).toLocaleString()}</td>
                    <td>👤 {item.uploadedBy}</td>
                    <td>
                      <span className={`status-badge ${item.status}`}>
                        {item.status === 'completed' && '✅ Completed'}
                        {item.status === 'processing' && '⏳ Processing'}
                        {item.status === 'failed' && '❌ Failed'}
                        {item.status === 'error' && '⚠️ Error'}
                      </span>
                    </td>
                    <td>
                      <div className="action-buttons">
                        {item.status === 'completed' && (
                          <>
                            <button
                              className="btn-action btn-view"
                              onClick={() => onViewDashboard(item.jobId)}
                              title="View Executive Dashboard"
                            >
                              📈 Dashboard
                            </button>
                            <a
                              href={`/api/ppt/${item.jobId}`}
                              className="btn-action btn-ppt"
                              download
                              title="Download PowerPoint Presentation"
                            >
                              📊 PPT
                            </a>
                            <a
                              href={`/api/report/${item.jobId}`}
                              className="btn-action btn-log"
                              download
                              title="Download Validation Report"
                            >
                              📝 Report
                            </a>
                          </>
                        )}
                        {item.error && (
                          <span className="error-tooltip" title={item.error}>
                            ⚠️ Error details
                          </span>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
