const fs = require('fs');
const path = require('path');

const canonicalOtherActivities = [
  {
    Subject: "Port Reset | JFL, Nagpur",
    Description: "Port Reset | JFL, Nagpur",
    SubCategory: "Change Request",
    Category: "Change Request",
    DeviceName: "Nagpur",
    Location: "Nagpur",
    DeviceSerial: "Q5JJ-68KZ-MXAS",
    SerialNo: "Q5JJ-68KZ-MXAS",
    DeviceID: "Q5JJ-68KZ-MXAS",
    DeviceType: "SW",
    Hostname: "JFL-NAG-SSC-SW01",
    Status: "Closed",
    RCA: "New Configuration",
    display_reference: "Ticket: CR-NAG-01"
  },
  {
    Subject: "Creating new user for BLR-SCC-GUEST SSID - Q3AC-Y2HS-V29M",
    Description: "Creating new user for BLR-SCC-GUEST SSID - Q3AC-Y2HS-V29M",
    SubCategory: "Change Request",
    Category: "Change Request",
    DeviceName: "Bangalore",
    Location: "Bangalore",
    DeviceSerial: "Q3AC-Y2HS-V29M",
    SerialNo: "Q3AC-Y2HS-V29M",
    DeviceID: "Q3AC-Y2HS-V29M",
    DeviceType: "AP",
    Hostname: "1F-AP26-R5-SW02-34P",
    Status: "Closed",
    RCA: "New Configuration",
    display_reference: "Ticket: CR-BLR-01"
  },
  {
    Subject: "Remove port security on the ports listed below on the mentioned switches. || FCW2222B4KE and FVH2914L0BV",
    Description: "Remove port security on the ports listed below on the mentioned switches. || FCW2222B4KE and FVH2914L0BV",
    SubCategory: "Change Request",
    Category: "Change Request",
    DeviceName: "Greater Noida",
    Location: "Greater Noida",
    DeviceSerial: "FVH2914L0BV",
    SerialNo: "FVH2914L0BV",
    DeviceID: "FVH2914L0BV",
    DeviceType: "SW",
    Hostname: "JFL-GNSC-GF-AC-SW-03",
    Status: "Closed",
    RCA: "New Configuration",
    display_reference: "Ticket: CR-GN-01"
  },
  {
    Subject: "Port Security Remove on Switch Port 2/0/2 – JFL-GNSC-ER-AC-SW-01",
    Description: "Port Security Remove on Switch Port 2/0/2 – JFL-GNSC-ER-AC-SW-01",
    SubCategory: "Change Request",
    Category: "Change Request",
    DeviceName: "Greater Noida",
    Location: "Greater Noida",
    DeviceSerial: "FOC2536Y0JD",
    SerialNo: "FOC2536Y0JD",
    DeviceID: "FOC2536Y0JD",
    DeviceType: "SW",
    Hostname: "JFL-GNMC-ER-AC-SW-01",
    Status: "Closed",
    RCA: "New Configuration",
    display_reference: "Ticket: CR-GN-02"
  },
  {
    Subject: "Enable Port 24 on switch 1F-R2-SW1 and assign it to VLAN 9. || Q2QW-EXJY-SE64",
    Description: "Enable Port 24 on switch 1F-R2-SW1 and assign it to VLAN 9. || Q2QW-EXJY-SE64",
    SubCategory: "Change Request",
    Category: "Change Request",
    DeviceName: "Bangalore",
    Location: "Bangalore",
    DeviceSerial: "Q2QW-EXJY-SE64",
    SerialNo: "Q2QW-EXJY-SE64",
    DeviceID: "Q2QW-EXJY-SE64",
    DeviceType: "SW",
    Hostname: "1F-R2-SW1",
    Status: "Closed",
    RCA: "New Configuration",
    display_reference: "Ticket: CR-BLR-02"
  },
  {
    Subject: "ISE Advantage Licence",
    Description: "ISE Advantage Licence",
    SubCategory: "Request Fulfillment",
    Category: "Request Fulfillment",
    DeviceName: "Noida",
    Location: "Noida",
    DeviceSerial: "WMP27030033",
    SerialNo: "WMP27030033",
    DeviceID: "WMP27030033",
    DeviceType: "Cisco ISE",
    Hostname: "JFL-ISE",
    Status: "Closed",
    RCA: "Others",
    display_reference: "Ticket: RF-NOI-01"
  },
  {
    Subject: "Network Asset Scan Reports---FOC2635Y89M",
    Description: "Network Asset Scan Reports---FOC2635Y89M",
    SubCategory: "Request Fulfillment",
    Category: "Request Fulfillment",
    DeviceName: "Noida",
    Location: "Noida",
    DeviceSerial: "FOC2635Y89M",
    SerialNo: "FOC2635Y89M",
    DeviceID: "FOC2635Y89M",
    DeviceType: "SW",
    Hostname: "JFL-Core-Sw1",
    Status: "Ticket Assignment",
    RCA: "On Hold",
    display_reference: "Ticket: RF-NOI-02"
  },
  {
    Subject: "Fw: Request to Switch Off Unnecessary Power Loads During BESCOM Shutdown.",
    Description: "Fw: Request to Switch Off Unnecessary Power Loads During BESCOM Shutdown.",
    SubCategory: "Request Fulfillment",
    Category: "Request Fulfillment",
    DeviceName: "Bangalore",
    Location: "Bangalore",
    DeviceSerial: "Q2DW-EM6A-8GPL",
    SerialNo: "Q2DW-EM6A-8GPL",
    DeviceID: "Q2DW-EM6A-8GPL",
    DeviceType: "SW",
    Hostname: "CORE-1",
    Status: "Closed",
    RCA: "On Hold",
    display_reference: "Ticket: RF-BLR-01"
  },
  {
    Subject: "Need to IP WHITELIST ---------10.167.6.119",
    Description: "Need to IP WHITELIST ---------10.167.6.119",
    SubCategory: "Change Request",
    Category: "Change Request",
    DeviceName: "Bangalore",
    Location: "Bangalore",
    DeviceSerial: "Q2QW-FCJL-LJS8",
    SerialNo: "Q2QW-FCJL-LJS8",
    DeviceID: "Q2QW-FCJL-LJS8",
    DeviceType: "SW",
    Hostname: "SEC-CAB-SW1",
    Status: "Closed",
    RCA: "New Configuration",
    display_reference: "Ticket: CR-BLR-03"
  },
  {
    Subject: "Need to IP WHITELIST ---------10.167.6.123",
    Description: "Need to IP WHITELIST ---------10.167.6.123",
    SubCategory: "Change Request",
    Category: "Change Request",
    DeviceName: "Bangalore",
    Location: "Bangalore",
    DeviceSerial: "Q2QW-FCJL-LJS8",
    SerialNo: "Q2QW-FCJL-LJS8",
    DeviceID: "Q2QW-FCJL-LJS8",
    DeviceType: "SW",
    Hostname: "SEC-CAB-SW1",
    Status: "Closed",
    RCA: "New Configuration",
    display_reference: "Ticket: CR-BLR-04"
  },
  {
    Subject: "Need to IP WHITELIST ---------10.167.6.120",
    Description: "Need to IP WHITELIST ---------10.167.6.120",
    SubCategory: "Change Request",
    Category: "Change Request",
    DeviceName: "Bangalore",
    Location: "Bangalore",
    DeviceSerial: "Q2QW-FCJL-LJS8",
    SerialNo: "Q2QW-FCJL-LJS8",
    DeviceID: "Q2QW-FCJL-LJS8",
    DeviceType: "SW",
    Hostname: "SEC-CAB-SW1",
    Status: "Closed",
    RCA: "New Configuration",
    display_reference: "Ticket: CR-BLR-05"
  },
  {
    Subject: "ALLOW MAC ADDRESS 60:3e:5f:7b:a9:47 JFL WIFI",
    Description: "ALLOW MAC ADDRESS 60:3e:5f:7b:a9:47 JFL WIFI",
    SubCategory: "Change Request",
    Category: "Change Request",
    DeviceName: "Bangalore",
    Location: "Bangalore",
    DeviceSerial: "Q2QW-FCJL-LJS8",
    SerialNo: "Q2QW-FCJL-LJS8",
    DeviceID: "Q2QW-FCJL-LJS8",
    DeviceType: "SW",
    Hostname: "SEC-CAB-SW1",
    Status: "Closed",
    RCA: "New Configuration",
    display_reference: "Ticket: CR-BLR-06"
  },
  {
    Subject: "ALLOW MAC ADDRESS 8e:49:15:8d:86:55 JFL WIFI",
    Description: "ALLOW MAC ADDRESS 8e:49:15:8d:86:55 JFL WIFI",
    SubCategory: "Change Request",
    Category: "Change Request",
    DeviceName: "Bangalore",
    Location: "Bangalore",
    DeviceSerial: "Q2QW-FCJL-LJS8",
    SerialNo: "Q2QW-FCJL-LJS8",
    DeviceID: "Q2QW-FCJL-LJS8",
    DeviceType: "SW",
    Hostname: "SEC-CAB-SW1",
    Status: "Closed",
    RCA: "New Configuration",
    display_reference: "Ticket: CR-BLR-07"
  },
  {
    Subject: 'Scheduled maintenance for 1 network(s) in organization "Jubilant Foods"',
    Description: 'Scheduled maintenance for 1 network(s) in organization "Jubilant Foods"',
    SubCategory: "IOS Upgradation Activity",
    Category: "IOS Upgradation Activity",
    DeviceName: "Greater Noida",
    Location: "Greater Noida",
    DeviceSerial: "Q5AR-527V-Z8YR",
    SerialNo: "Q5AR-527V-Z8YR",
    DeviceID: "Q5AR-527V-Z8YR",
    DeviceType: "AP",
    Hostname: "JFL-GNSC-AP23",
    Status: "Ticket Assignment",
    RCA: "On Hold",
    display_reference: "Ticket: MA-GN-01"
  },
  {
    Subject: 'Scheduled maintenance for 1 network(s) in organization "Jubilant Foodworks Ltd"',
    Description: 'Scheduled maintenance for 1 network(s) in organization "Jubilant Foodworks Ltd"',
    SubCategory: "IOS Upgradation Activity",
    Category: "IOS Upgradation Activity",
    DeviceName: "Greater Noida",
    Location: "Greater Noida",
    DeviceSerial: "Q5AR-527V-Z8YR",
    SerialNo: "Q5AR-527V-Z8YR",
    DeviceID: "Q5AR-527V-Z8YR",
    DeviceType: "AP",
    Hostname: "JFL-GNSC-AP23",
    Status: "Ticket Assignment",
    RCA: "On Hold",
    display_reference: "Ticket: MA-GN-02"
  },
  {
    Subject: "JFL Network Asset Scan Report",
    Description: "JFL Network Asset Scan Report",
    SubCategory: "Request Fulfillment",
    Category: "Request Fulfillment",
    DeviceName: "Noida",
    Location: "Noida",
    DeviceSerial: "FOC2635Y89T",
    SerialNo: "FOC2635Y89T",
    DeviceID: "FOC2635Y89T",
    DeviceType: "SW",
    Hostname: "JFL-Core-Sw2",
    Status: "Ticket Assignment",
    RCA: "On Hold",
    display_reference: "Ticket: RF-NOI-03"
  },
  {
    Subject: "Guest Wi-Fi Credentials Required-KPMG Audit",
    Description: "Guest Wi-Fi Credentials Required-KPMG Audit",
    SubCategory: "Change Request",
    Category: "Change Request",
    DeviceName: "Greater Noida",
    Location: "Greater Noida",
    DeviceSerial: "Q5AA-Z3WW-CY6C",
    SerialNo: "Q5AA-Z3WW-CY6C",
    DeviceID: "Q5AA-Z3WW-CY6C",
    DeviceType: "AP",
    Hostname: "JFL-GNSC-AP05",
    Status: "On Hold",
    RCA: "On Hold",
    display_reference: "Ticket: CR-GN-03"
  }
];

const targetFiles = [
  path.resolve('data', 'dashboard_data.json'),
  path.resolve('data', 'bundled_default', 'dashboard_data.json'),
  path.resolve('frontend', 'src', 'data', 'defaultDashboardData.json')
];

targetFiles.forEach((file) => {
  if (fs.existsSync(file)) {
    const data = JSON.parse(fs.readFileSync(file, 'utf8'));
    data.otherActivities = canonicalOtherActivities;
    fs.writeFileSync(file, JSON.stringify(data, null, 2));
    console.log(`Updated ${path.relative(process.cwd(), file)} with ${canonicalOtherActivities.length} otherActivities records.`);
  }
});
